name: generate-dto-ts

on:
  push:
    branches: [ main ]

jobs:
  upload-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Server Repository
        uses: actions/checkout@v4
        with:
          path: 'sercver'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Generate dto.ts
        run: |
          cd sercver
          ./gradlew generateDto

      - name: Checkout Web Repository
        uses: actions/checkout@v4
        with:
          repository: 'dwhale-theo/web'
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          path: 'web'
          ref: 'new-feature-branch5'
          fetch-depth: 0          

      - name: Copy DTO File to Target Repository
        run: |
          cp sercver/build/dto/dto.d.ts web/

      - name: Commit and Push Changes to Target Repository
        uses: EndBug/add-and-commit@v7
        with:
          cwd: 'web'
          add: 'dto.d.ts'
          message: 'Update DTO definitions'
          branch: 'new-feature-branch5'
        env:
          GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}

      
