name: generate-dto-ts

on:
  push:
    branches: [ main ]

jobs:
  upload-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout Web Repository
        uses: actions/checkout@v4
        with:
          repository: 'dwhale-theo/web'
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          ref: 'new-feature-branch'
          fetch-depth: 0            
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          branch: 'new-feature-branch'
          title: 'Update DTO Definitions'
          body: 'Please review the updated DTO definitions.'
          base: 'main'
