name: Create Pull Request on Push to Main

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: new-feature-branch2 # Ensure we are checking out the "PR" branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          commit-message: "Auto-update Main Branch"
          title: "Merge PR into Main"
          body: "This is an automated pull request to update the main branch with changes from PR."
          branch: new-feature-branch2
          base: main
          delete-branch: false
          draft: false
